// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: my_gRPC/my_gRPC.proto

package My_gRPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//!< Keeps a type of message.
	Prm1 float32 `protobuf:"fixed32,1,opt,name=prm1,proto3" json:"prm1,omitempty"`
	//!< Keeps a value.
	Prm2 float32 `protobuf:"fixed32,2,opt,name=prm2,proto3" json:"prm2,omitempty"`
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_my_gRPC_my_gRPC_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_my_gRPC_my_gRPC_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_my_gRPC_my_gRPC_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetPrm1() float32 {
	if x != nil {
		return x.Prm1
	}
	return 0
}

func (x *SendRequest) GetPrm2() float32 {
	if x != nil {
		return x.Prm2
	}
	return 0
}

type SendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//!< Keeps a status of request.
	Result float32 `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_my_gRPC_my_gRPC_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_my_gRPC_my_gRPC_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_my_gRPC_my_gRPC_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_my_gRPC_my_gRPC_proto protoreflect.FileDescriptor

var file_my_gRPC_my_gRPC_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x79, 0x5f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x6d, 0x79, 0x5f, 0x67, 0x52, 0x50,
	0x43, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x79, 0x5f, 0x67, 0x52, 0x50, 0x43,
	0x22, 0x35, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x72, 0x6d, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x70,
	0x72, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x6d, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x70, 0x72, 0x6d, 0x32, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0x45, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x33, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x6d, 0x79, 0x5f, 0x67,
	0x52, 0x50, 0x43, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x6d, 0x79, 0x5f, 0x67, 0x52, 0x50, 0x43, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x54, 0x68, 0x2f, 0x4d,
	0x79, 0x5f, 0x67, 0x52, 0x50, 0x43, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_my_gRPC_my_gRPC_proto_rawDescOnce sync.Once
	file_my_gRPC_my_gRPC_proto_rawDescData = file_my_gRPC_my_gRPC_proto_rawDesc
)

func file_my_gRPC_my_gRPC_proto_rawDescGZIP() []byte {
	file_my_gRPC_my_gRPC_proto_rawDescOnce.Do(func() {
		file_my_gRPC_my_gRPC_proto_rawDescData = protoimpl.X.CompressGZIP(file_my_gRPC_my_gRPC_proto_rawDescData)
	})
	return file_my_gRPC_my_gRPC_proto_rawDescData
}

var file_my_gRPC_my_gRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_my_gRPC_my_gRPC_proto_goTypes = []interface{}{
	(*SendRequest)(nil),  // 0: my_gRPC.SendRequest
	(*SendResponse)(nil), // 1: my_gRPC.SendResponse
}
var file_my_gRPC_my_gRPC_proto_depIdxs = []int32{
	0, // 0: my_gRPC.DatabusService.Send:input_type -> my_gRPC.SendRequest
	1, // 1: my_gRPC.DatabusService.Send:output_type -> my_gRPC.SendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_my_gRPC_my_gRPC_proto_init() }
func file_my_gRPC_my_gRPC_proto_init() {
	if File_my_gRPC_my_gRPC_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_my_gRPC_my_gRPC_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_my_gRPC_my_gRPC_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_my_gRPC_my_gRPC_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_my_gRPC_my_gRPC_proto_goTypes,
		DependencyIndexes: file_my_gRPC_my_gRPC_proto_depIdxs,
		MessageInfos:      file_my_gRPC_my_gRPC_proto_msgTypes,
	}.Build()
	File_my_gRPC_my_gRPC_proto = out.File
	file_my_gRPC_my_gRPC_proto_rawDesc = nil
	file_my_gRPC_my_gRPC_proto_goTypes = nil
	file_my_gRPC_my_gRPC_proto_depIdxs = nil
}
